#!/usr/bin/env bash
# Regenerate BOTH language bindings from format/Layout.fbs:
#   Java:  flatc --java  → ascham-core/src/generated/java/io/ascham/flatbuf/
#   C:     flatcc        → cpp/src/format/layout_generated.h  (reader + verifier only)
#
# Java requires flatc on PATH at exactly FLATC_VERSION — it must match the flatbuffers-java
# runtime pinned in ascham-core/build.gradle.kts. Release binaries:
# https://github.com/google/flatbuffers/releases/tag/v25.2.10
#
# C is hermetic, nanoarrow-style: clones and builds the flatcc compiler at FLATCC_TAG in a temp
# dir. The pin matches the flatcc RUNTIME vendored via the nanoarrow amalgamation
# (cpp/src/vendor/nanoarrow/src/flatcc.c, generated banners say 0.6.2) — generated code and
# runtime must agree. --common inlines flatbuffers_common_reader.h, which is not vendored
# standalone; no --builder, readers never write descriptors.
set -euo pipefail

FLATC_VERSION="25.2.10"
FLATCC_TAG="v0.6.2"
cd "$(dirname "$0")/.."

# --- Java (flatc) ---
actual="$(flatc --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"
if [[ "${actual}" != "${FLATC_VERSION}" ]]; then
    echo "error: flatc ${FLATC_VERSION} required (matches the flatbuffers-java runtime), got ${actual}" >&2
    exit 1
fi
rm -rf ascham-core/src/generated/java/io/ascham/flatbuf
flatc --java -o ascham-core/src/generated/java format/Layout.fbs
echo "regenerated ascham-core/src/generated/java/io/ascham/flatbuf/ with flatc ${FLATC_VERSION}"

# --- C (flatcc, hermetic) ---
OUT="cpp/src/format/layout_generated.h"
workdir="$(mktemp -d)"
trap 'rm -rf "${workdir}"' EXIT

git clone --quiet --depth 1 --branch "${FLATCC_TAG}" https://github.com/dvidelabs/flatcc.git "${workdir}/flatcc"
cmake -S "${workdir}/flatcc" -B "${workdir}/build" -DFLATCC_RTONLY=OFF -DFLATCC_TEST=OFF \
      -DCMAKE_BUILD_TYPE=Release >/dev/null
cmake --build "${workdir}/build" --target flatcc_cli >/dev/null

"${workdir}/flatcc/bin/flatcc" --common --reader --verifier --recursive \
    --outfile "${OUT}.tmp" format/Layout.fbs

{
    echo "// GENERATED by dev/update_flatbuffers.sh from format/Layout.fbs (flatcc ${FLATCC_TAG}) — DO NOT EDIT."
    echo "// The flatcc runtime it compiles against is the one vendored via nanoarrow"
    echo "// (cpp/src/vendor/nanoarrow/, same flatcc version)."
    cat "${OUT}.tmp"
} > "${OUT}"
rm "${OUT}.tmp"
echo "regenerated ${OUT} with flatcc ${FLATCC_TAG}"
