// Layout conformance vectors: (canonical schema bytes → LayoutCodec descriptor bytes) pairs
// generated by the Java writer (ascham's LayoutVectorGenerator, 512 random seeds + edge cases).
// The layout-derivation algorithm (Layouts.compute) is deliberately hand-written per language and
// pinned by these vectors instead of generated; a future non-Java *writer* must byte-compare its
// implementation against every pair. This reader has no layout derivation — what the vectors pin
// here is the decode side:
//   - every descriptor decodes cleanly, and its bytes hash to the recorded descriptor_sha256
//     (so the vendored file is internally consistent, like the golden corpus manifest);
//   - every buffer offset is 64-aligned, every stride page-aligned, every extent inside the
//     stride — the invariants the reader is entitled to assume of any writer;
//   - every schema decodes through the same nanoarrow path as a segment open, with a column
//     count matching its descriptor.
#include <cstdint>
#include <fstream>
#include <string>
#include <vector>

#include "format/arena_format.hpp"
#include "format/layout.hpp"
#include "format/layout_generated.h"
#include "format/schema.hpp"
#include "format/sha256.hpp"
#include "test_framework.hpp"

namespace {

std::vector<std::uint8_t> base64_decode(const std::string &in) {
    static const std::string alphabet =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    std::vector<std::uint8_t> out;
    out.reserve(in.size() / 4 * 3);
    unsigned buffer = 0;
    int bits = 0;
    for (char c : in) {
        if (c == '=') break;
        std::size_t v = alphabet.find(c);
        if (v == std::string::npos) {
            ::testfw::fail("invalid base64 character in layout vector", __FILE__, __LINE__);
        }
        buffer = (buffer << 6) | static_cast<unsigned>(v);
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            out.push_back(static_cast<std::uint8_t>((buffer >> bits) & 0xFF));
        }
    }
    return out;
}

// "key":"value" extraction; the vectors are generated one-object-per-line JSON with base64/hex
// payloads (no escapes), so a scan keeps the reader core's zero-dependency rule intact.
bool field(const std::string &s, const std::string &key, std::string &out) {
    std::size_t k = s.find("\"" + key + "\":\"");
    if (k == std::string::npos) return false;
    std::size_t start = k + key.size() + 4;
    std::size_t end = s.find('"', start);
    if (end == std::string::npos) return false;
    out = s.substr(start, end - start);
    return true;
}

std::string hex(const std::array<std::uint8_t, 32> &digest) {
    static const char *digits = "0123456789abcdef";
    std::string s;
    s.reserve(64);
    for (std::uint8_t b : digest) {
        s.push_back(digits[b >> 4]);
        s.push_back(digits[b & 0xf]);
    }
    return s;
}

}  // namespace

// The hand-written domain enum must agree value-for-value with format/Layout.fbs — the IDL is the
// wire-value assignment authority (the Java side asserts the same against its flatc bindings).
TEST(physical_kind_matches_layout_fbs) {
    CHECK_EQ(static_cast<int>(arena::PhysicalKind::FIXED), io_ascham_flatbuf_PhysicalKind_Fixed);
    CHECK_EQ(static_cast<int>(arena::PhysicalKind::VARLEN), io_ascham_flatbuf_PhysicalKind_Varlen);
    CHECK_EQ(static_cast<int>(arena::PhysicalKind::BOOL_BITMAP),
             io_ascham_flatbuf_PhysicalKind_BoolBitmap);
}

TEST(layout_vectors_decode_and_hold_invariants) {
    std::ifstream in(::testfw::conformance_dir() + "/layout_vectors.jsonl");
    if (!in) {
        ::testfw::fail("cannot open conformance/layout_vectors.jsonl", __FILE__, __LINE__);
    }
    int count = 0;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        std::string id, schema_b64, descriptor_b64, descriptor_sha;
        CHECK(field(line, "id", id));
        CHECK(field(line, "schema_b64", schema_b64));
        CHECK(field(line, "descriptor_b64", descriptor_b64));
        CHECK(field(line, "descriptor_sha256", descriptor_sha));

        auto descriptor = base64_decode(descriptor_b64);
        if (hex(arena::sha256(descriptor.data(), descriptor.size())) != descriptor_sha) {
            ::testfw::fail("vector '" + id + "': descriptor bytes do not match descriptor_sha256",
                           __FILE__, __LINE__);
        }

        auto layout = arena::LayoutDescriptor::decode(
            descriptor.data(), static_cast<std::int64_t>(descriptor.size()));
        CHECK(layout.batch_rows > 0);
        CHECK(layout.batch_stride_bytes > 0);
        CHECK_EQ(layout.batch_stride_bytes % arena::fmt::PAGE_ALIGN, 0);
        CHECK(!layout.columns.empty());
        for (const auto &col : layout.columns) {
            CHECK_EQ(col.validity_offset % arena::fmt::BUFFER_ALIGN, 0);
            CHECK_EQ(col.data_offset % arena::fmt::BUFFER_ALIGN, 0);
            CHECK(col.data_offset + col.data_capacity_bytes <= layout.batch_stride_bytes);
            if (col.is_varlen()) {
                CHECK_EQ(col.offsets_offset % arena::fmt::BUFFER_ALIGN, 0);
                CHECK(col.offsets_offset < col.data_offset);
            } else {
                CHECK_EQ(col.offsets_offset, -1);
            }
        }

        auto schema_bytes = base64_decode(schema_b64);
        auto schema = arena::TableSchema::decode(schema_bytes.data(), schema_bytes.size());
        CHECK_EQ(schema.columns.size(), layout.columns.size());
        CHECK(!schema.time_column.empty());
        ++count;
    }
    // 512 random seeds + the named edge cases; a shorter file is a broken sync.
    CHECK(count >= 520);
}
